<a href="https://colab.research.google.com/github/Bluelord/ML_Mastery_Python/blob/main/05_Pre_Process_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prepare Your Data
---


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


This step the is most important step before preparing the ML model, in this 4 different pre-processing techniques is show (Rescale, Standerdize, Normalize and Binarize the data). Each processing steps follows loading of data, spliting (input and output), transformation then sammarizing the changes.

scikit-learn provide two ways for transforming data, they are used depanding upon the cercumstances.
*   **Fit & Multiple Transformation** is most prefered, in this **fit()** function gives us the parameters onces for our dataset then the **transform()** is used for modeling on test or on the validating dataset.
*   **Combined Fit-&-Transform** is used when we are interesed in ploting & summarizing the transformation.



## Rescalr Data

When data has varities of scales, ofthen used in algorithms like gradient desent or in weight inputs like regression models, neural networks or in the algorithum uses distance measures like KNN. **MinMaxScaler()** function is used for this.



In [2]:
# Rescale Data (Between 0 & 1)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
filename = "/content/drive/MyDrive/Colab Notebooks/ML Mastery python/Dataset/pima-indians-diabetes.csv"
names = ['preg', 'plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
# separate array into input & output 
X = array[:,0:8]
Y = array[:,8]
##########################################
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
###########################################
#Summarize transformation 
set_printoptions(precision=3)
print(rescaledX[:,:])

[[0.353 0.744 0.59  ... 0.501 0.234 0.483]
 [0.059 0.427 0.541 ... 0.396 0.117 0.167]
 [0.471 0.92  0.525 ... 0.347 0.254 0.183]
 ...
 [0.294 0.608 0.59  ... 0.39  0.071 0.15 ]
 [0.059 0.633 0.492 ... 0.449 0.116 0.433]
 [0.059 0.467 0.574 ... 0.453 0.101 0.033]]


## Standardize Data

Standardization is a useful technique to transform attributes with a Gaussian distribution and differing means and standard deviations to a standard Gaussian distribution with a mean of 0 and a standard deviation of 1. It is most suitable for techniques that assume a Gaussian distribution in the input variables and work better with rescaled data.



In [3]:
# Standardize data (0 mean, 1 std )
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
set_printoptions(precision=3)
print(rescaledX[:,:])

[[ 0.64   0.848  0.15  ...  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161 ... -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 ... -1.103  0.604 -0.106]
 ...
 [ 0.343  0.003  0.15  ... -0.735 -0.685 -0.276]
 [-0.845  0.16  -0.471 ... -0.24  -0.371  1.171]
 [-0.845 -0.873  0.046 ... -0.202 -0.474 -0.871]]


## Normalization

This Method can be usfull for the dataset which have too much of zeros in its features. This method is usfull for algorithm which used weight input values or for the distance measuring models.  Normalizer() is used for tranforming the data.



In [4]:
# Normalize data (length 1)
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X)
NormalizedX = scaler.transform(X)
set_printoptions(precision=3)
print(NormalizedX[:,:])

[[0.034 0.828 0.403 ... 0.188 0.004 0.28 ]
 [0.008 0.716 0.556 ... 0.224 0.003 0.261]
 [0.04  0.924 0.323 ... 0.118 0.003 0.162]
 ...
 [0.027 0.651 0.388 ... 0.141 0.001 0.161]
 [0.007 0.838 0.399 ... 0.2   0.002 0.313]
 [0.008 0.736 0.554 ... 0.241 0.002 0.182]]


## Binarize the Data

In this method the dataset is divided into two values with the help of binary threshold, in which the data above the threshold is marked as 1 & below data as 0. 
It is useful when we want to make crip values or for adding new meaning feature in our dataset.



In [5]:
# Binarization
from sklearn.preprocessing import Binarizer
binarize = Binarizer(threshold=0).fit(X)
binaryX = binarize.transform(X)
set_printoptions(precision=1)
print(rescaledX[0:5,:])

[[ 0.6  0.8  0.1  0.9 -0.7  0.2  0.5  1.4]
 [-0.8 -1.1 -0.2  0.5 -0.7 -0.7 -0.4 -0.2]
 [ 1.2  1.9 -0.3 -1.3 -0.7 -1.1  0.6 -0.1]
 [-0.8 -1.  -0.2  0.2  0.1 -0.5 -0.9 -1. ]
 [-1.1  0.5 -1.5  0.9  0.8  1.4  5.5 -0. ]]
